config/routes.rb
Rails.application.routes.draw do


  get 'callbacks/twitter'

  # get 'http://127.0.0.1:3000/auth/twitter/'
  get '/auth/twitter', as: :sign_in_with_twitter
  get '/auth/twitter/callback' => 'callbacks#twitter'

  # get '/auth/facebook?display=popup', as: :sign_in_with_facebook
  get '/auth/facebook', as: :sign_in_with_facebook
  get '/auth/facebook/callback' => 'callbacks#facebook'

  # get 'tags/index'
  #
  # get 'tags/show'
  resources :tags, only: [:index, :show]


  namespace :admin do
    get 'questions/index'
  end

  resources :products, shallow: true do
    # resources :products do

    resources :favourites, only: [:create, :destroy]
    resources :reviews
  end

  resources :users, only: [:new, :create]

  resources :sessions, only: [:new, :create] do
    delete :destroy, on: :collection

  end


  namespace :api, default: {format: 'json'} do
    namespace :v1 do
      resources :products
    end
  end


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get "/test" => "test#query"

  get "/" => "welcome#home", as: :home
  get "/about" => "welcome#about"
  get "/contact" => "welcome#contact"
  post "/contact_submit" => "welcome#contact_submit"
  get "/admin/questions/index" => "admin/questions#index"


end

app/models/product.rb
class Product < ApplicationRecord
  has_many :reviews, dependent: :destroy
  belongs_to :category
  belongs_to :user
  has_many :favourites, dependent: :destroy
  has_many :users, through: :favourites
  has_many :taggings, dependent: :destroy
  has_many :tags, through: :taggings


  validates :title, :presence => true, :uniqueness => {:case_sensitive => false}
  validates :title, :presence => true, :uniqueness => true
  validates :price, :presence => true
  validates :sales_price, :numericality => {less_than: :price}
  after_initialize :init_config

  def init_config
    self.sales_price||= 5
  end

  def is_sales?
    # self.price>self.sales_price
    self.price>sales_price
  end

  def favour_by?(user)
    # likes.find_by_user_id(user.id).present?
    favourites.find_by(user_id: user.id).present?
  end

  # validates (:price, {numericality: {greater_than: 1}})
  # validates :description, length: { maximum: 10 }


  # def search(words)
  #
  #
  # end


end

app/controllers/api/v1/products_controller.rb
class Api::V1::ProductsController < ApplicationController

  protect_from_forgery with: :null_session
  before_action :authentication


  def index
    @products=Product.order("created_at DESC").limit(10)
    # respond_to do |format|
    #   format.json { render json: @products }
    #
    # end
    render json: @products


  end

  def create
    # render json: {a: 'b'}
    product_params=params.require(:product).permit([:title, :description, :price])

    product=Product.new(product_params)
    if product.save
      render json: {id: product.id, status: 'create success'}

    else
      render json: {status: 'create failure', error: product.errors.full_messages.join(',')}


    end

  end

  def update
    # render json: {a: 'b'}
    product_params=params.require(:product).permit([:title, :description, :price])

    product=Product.find_by(id:params[:id])
    if product
      product.update(product_params)
      render json: {id: product.id, status: 'update success'}

    else
      render json: {status: 'update failure', error: product.errors.full_messages.join(',')}

    end

  end

  def destroy
    product_id=params[:id]
    product=Product.find_by(id: product_id)
    if product
      product.destroy
      render json: {status: "success to delete"}
    else
      render json: {status: "failure to delete,because product is not avaiable"}


    end


  end


  private
  def authentication

    user=User.find_by(api_key: params[:api_key])

    head :unauthorized unless user


  end


end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :authenticate_user, except: [:show, :index]

  def new
    @p=Product.new
    @c=Category.all
  end

  def create
    arr=params[:pet]

    user=current_user

    product_param=get_params
    @p=Product.new(product_param)
    @p.user =user
    if @p.save
      client = Twitter::REST::Client.new do |config|
        config.consumer_key = 'mAAmYVTjITQhINfzAJpH9Z26S'
        config.consumer_secret ="mRg2POmRug7QrskWuvu8H0uLKMX2oXXv1YxQEoD8yin9IJ8wcE"
        config.access_token = user.token
        config.access_token_secret = user.secret
      end
      client.update(@p.title)

      # render plain: "hi"
      redirect_to product_path(@p)
    else
      render :new
    end

  end

  def show
    @p= Product.find(params[:id])
    @review=Review.new
    respond_to do |format|
      format.html { render }
      # http://localhost:3000/products/1.json
      format.json { render json: @p.to_json }
    end
  end

  def index
    @ps=Product.all
    respond_to do |format|
      format.html { render }
      # http://localhost:3000/products.json
      format.json { render json: @ps.to_json }

    end

  end

  def destroy
    @p=Product.find(params[:id])
    @p.destroy

    redirect_to products_path


  end

  def edit
    @p=Product.find params[:id]

  end

  def update
    # product_param=params.require(:product).permit(:title, :description, :price, :category_id,tag_ids: [])
    product_param=get_params


    @p=Product.find(params[:id])
    @p.update(product_param)
    redirect_to product_path(@p)

  end

  private
  def get_params
    params.require(:product).permit(:title, :description, :price, :category_id, tag_ids: [])
  end

end

app/helpers/api/v1/products_helper.rb
module Api::V1::ProductsHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/products/edit.html.erb
<%= form_for @p  do |f|%>
    <div>
      <%= f.label :title %>
      <%= f.text_field :title %>

    </div>
    <div>
      <%= f.label :description %>
      <%= f.text_field :description %>

    </div>
    <div>
      <%= f.label :price %>
      <%= f.text_field :price %>

    </div>

    <div>
      <%= f.collection_select(:category_id,Category.all,:id,:name) %>

    </div>

    <div>
      <%= f.collection_select(:tag_ids, Tag.all, :id, :name,{},{multiple:true,class:'chosen-select'}) %>


    </div>
    <%= f.submit %>



<% end %>


<script type="text/javascript" charset="utf-8">
  $('.chosen-select').chosen({width: '200px'});
</script>

app/views/products/index.html.erb
<% @ps.each do |p| %>
    <div>
       <%= link_to p.title,product_path(p) %>
      <!--<%= p.title %>-->
      <%= p.description %>
      $<%= p.price.round(3) %>
      <%= p.category.name if p.category %>
    </div>


<% end %>

app/views/products/new.html.erb
<%= form_for @p do |f| %>
    <div>
      <%= f.label :title %>
      <%= f.text_field :title %>

    </div>
    <div>
      <%= f.label :description %>
      <%= f.text_field :description %>

    </div>
    <div>
      <%= f.label :price %>
      <%= f.text_field :price %>

    </div>

    <div>
      <%= f.collection_select(:category_id, Category.all, :id, :name) %>


    </div>

    <div>
      <%= f.collection_select(:tag_ids, Tag.all, :id, :name,{},{multiple:true,class:'chosen-select'}) %>


    </div>
    <%= f.submit %>



<% end %>

<% if false %>

    <%= form_tag products_path do %>

        <%= check_box_tag(:pets, "dog") %>I own a dog
        <%= check_box_tag(:pets, "cat") %>I own a cat
        <%= submit_tag %>

    <% end %>


    <%= form_tag products_path do %>


        <%= radio_button_tag(:pets, "dog") %>I own a dog
        <%= radio_button_tag(:pets, "cat") %>I own a cat
        <%= submit_tag %>

    <% end %>


    <%= form_tag products_path do %>


        <%= select_tag "pet", raw("<option value='David'>David</option> <option value='John'>John</option>") %>

        <%= submit_tag %>

    <% end %>

<% end %>


<script type="text/javascript" charset="utf-8">
  $('.chosen-select').chosen({width: '200px'});
</script>

app/views/products/show.html.erb
<br>
<%= @review.errors.full_messages.join(",") %>
<br>
<div>
  <h1><%= @p.title %></h1>
  <%= @p.description %>
  <%= @p.price %>
  <%= @p.category.name %>
  <%= link_to "Delete", product_path(@p), method: :delete %>
  <%= link_to "Edit", edit_product_path(@p) %>

  <br>
  <div id="favouritezzzzzz">
   <%= render 'favourites/favourite',product:@p %>

  </div>


  <br>

  <section class="tag-widge">
    <h1>Tagging</h1>
    <% tag_arr=@p.tags.map { |tag| tag.name } %>
    <%= tag_arr.join(" , ") %>
  </section>


</div>


<h2>Reviews</h2>


<div id="review-form">
  <%= render 'reviews/form' %>

</div>


<div id="reviews">
  <% @p.reviews.each do |review| %>

      <%= render 'reviews/review', review: review %>

  <% end %>


</div>